### PR TITLE
Translation of yule.R to yule.jl

### PR DESCRIPTION
**Pull request by akulumbeg**
As Julia does not seem to have an ubiquotuous function like summary(), I wrote a workaround where all the values of summary() called on a linear model object in R are printed out separately. 

Should this be more verbose with the print function? E.g. print("The R^2 value is XY.Z")

### CODE REVIEW

**Comment by dwinkler1** [comment]
There is https://github.com/jmboehm/RegressionTables.jl but I don't think its necessary. What is missing from the regular print output?

**Comment by akulumbeg** [comment]
I was looking at RegressionTables already but with GLM there is a known issue where some field will be left blank (documented here: https://github.com/jmboehm/RegressionTables.jl/issues/52) 

I left that code as an alternative and rather than that, I used the FixedEffectModels package with RegressionTables.jl. However, there is yet another issue, where FEM shows incorrect Degrees of Freedom (known issue - https://github.com/FixedEffects/FixedEffectModels.jl/issues/78) but in RegressionTables, everything is correct.

In any case, we need to make the code crystal clear, so we either have to wait for a patch or have to patch this by ourselves somehow... ?

**Comment by dwinkler1** [comment]
Probably not worth it. I think its fine like this. Personally i think its even better than the random statistics in the default r summary.

**Comment by akulumbeg** [comment]
OK perfect. I managed to sneak in a translation of independence.R, review that too plz, although it seems to be working just fine. I just wonder if there is a more efficient way of "pulling" a column as a vector out of a DF.jl than what I did (convert(Array,col)).

**Comment by dwinkler1** [comment]
Internally columns are just regular Julia arrays so we can just index into it with

`_.y` 

In the last row and would also not need the select before.

**Comment by dwinkler1** [comment]
Actually what do you think about:
```

    sd0 = @chain df begin
        sort!(:random) 
        insertcols!(:d => vcat(fill(1,5), fill(0,5)))
        select!([:d, :y1, :y0] => 
                ByRow((d,y1,y0) -> d * y1 + (1 - d) * y0) => :y)
        _.y
    end
```

The `select!` follows the DataFrames minilanguage more and the transformation is much more readable but also longer.

**Comment by akulumbeg** [comment]
Exactly what I was looking for but couldn`t find! If you could replace it with that code, it would be great :)

**Comment by dwinkler1** [comment]
BTW just for posterity `df.y` is shorthand for `getproperty(df, :y)` so we could also write `getproperty(:y)`

**Pull request merged**
